; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local void @test_vcmulas_s8_qacc_h(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmulas_s8_qacc_h:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s8.qacc.h q0, q1
; ASM-NEXT:    esp.st.qacc.h.l.128.ip a2, 16
; ASM-NEXT:    esp.st.qacc.h.h.128.ip a2, 16
; ASM-NEXT:    ret
entry:
  %z = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %qh_l = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %z, 2
  %qh_h = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %z, 3
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %qx = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %qy = extractvalue { <16 x i8>, ptr } %vld2, 0
  %acc = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.h(<16 x i8> %qh_l, <16 x i8> %qh_h, <16 x i8> %qx, <16 x i8> %qy, i32 0)
  %out_l = extractvalue { <16 x i8>, <16 x i8> } %acc, 0
  %out_h = extractvalue { <16 x i8>, <16 x i8> } %acc, 1
  %p1 = tail call ptr @llvm.riscv.esp.st.qacc.h.l.128.ip(<16 x i8> %out_l, ptr %dst, i32 16)
  tail call ptr @llvm.riscv.esp.st.qacc.h.h.128.ip(<16 x i8> %out_h, ptr %p1, i32 16)
  ret void
}

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc() nounwind
declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32 immarg) nounwind
declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.h(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32 immarg) nounwind
declare ptr @llvm.riscv.esp.st.qacc.h.l.128.ip(<16 x i8>, ptr, i32 immarg) nounwind
declare ptr @llvm.riscv.esp.st.qacc.h.h.128.ip(<16 x i8>, ptr, i32 immarg) nounwind

attributes #0 = { nounwind vscale_range(1,1) }
